<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>An error ocured</title>
	<style>
		body { font: 15px Arial, sans-serif; height: 1vh; width: 100%; margin: 0; padding: 0; }
		.container { width: 800px; margin: auto; }
	</style>
</head>
<body>
	<div class="container">
		<?= $massage ?>
	</div>
</body>
</html>